### ISSUE TITLE
Video Demo Request

### ISSUE THREAD

**Issue by NicoHinderling** [dedmonkes/Decentralised-Social#22]
Hi there,

Would it be possible to add a recorded video of your web app tool running to the README?

Thanks!

**Comment by professormint** [comment]
Sorry just seeing this. I have added a short video to the readme.

Here is a link to the video also 

https://drive.google.com/file/d/1LgB-7YK9YZ-CNsWEKGFeb1ySzUILORKj/view?usp=sharing

Thanks
